mozilla/fxa-customs-server

bans/sqs.js, bin/customs_server.js, npm-shrinkwrap.json, package.json
This will give slightly more helpful log messages when we fail to process from the sqs ban queue.  @chilts r?
=> Tweak logging output when processing sqs ban messages.

README.md
fixes #77
@dannycoates, @rfk or @chilts, could you give this a quick read?
=> feat(docs): Include a snipped about the memcached requirement.

email_record.js, ip_email_record.js
This addresses a couple of nits we had left over from #71.  @chilts r?
=> More code cleanups

bans/handler.js, bin/customs_server.js, config/config.js, email_record.js, test/local/ban_tests.js, test/local/email_record_tests.js, test/memcache-helper.js, test/remote/too_many_bad_logins.js
This is the time over which bad logins should be remembered for account lockout
fixes #75
=> feat(config): Add a badLoginLockoutIntervalSeconds configuration option.

.travis.yml, scripts/test-local.sh
Notes: 
1. this was failing on some security warnings that I think are a little over-rated, so quieted them
2. However, it is perhaps time to do a refresh of some modules, and I'll file a follow up issue for that.
=> Test travis 0.12 iojs

.travis.yml, grunttasks/nsp.js, npm-shrinkwrap.json, package.json
Fixes https://github.com/mozilla/fxa-customs-server/issues/91
=> fix(build): add grunt-nsp

npm-shrinkwrap.json, package.json, scripts/config-list.js, scripts/config-set.js
@jrgm is this good enough or do you want more fancy?
=> some *sharp* tools for updating the configs in memcache

scripts/block-ip.js, scripts/customs-info.js
=> feat(scripts): added admin scripts: block-ip and customs-info

.gitignore, .travis.yml, package.json
=> fix(tests): add coveralls and enforce coverage

README.md, lib/actions.js, test/local/ban_tests.js, test/memcache-helper.js, test/remote/too_many_bad_logins.js
A couple of stray references to account lockout that I noticed in passing; @shane-tomlinson r?
=> chore(server): Remove some left-over references to account lockout.

test/memcache-helper.js, test/remote/block_email_tests.js, test/remote/block_ip_tests.js, test/remote/email_normalization.js, test/remote/never_blocked.js, test/remote/password_reset_clears_bad_logins.js, test/remote/too_many_bad_logins.js, test/remote/too_many_emails.js
=> refactor(test): Modify test cases to use promises instead of callbacks

lib/server.js
Return an explicit `unblock` key in more places; @seanmonstar r?
=> fix(unblock): Return `unblock` value for IPs on a blocklist

.gitignore, lib/config/config.js, lib/requestChecks.js, lib/server.js, scripts/config-list.js, scripts/config-set.js, test/local/ip_blocklist_tests.js, test/memcache-helper.js, test/remote/block_ip_tests.js, test/remote/config_update_tests.js
Fixes https://github.com/mozilla/fxa-customs-server/issues/126
@vbudhram r?
=> feat(requestChecks): Backport "requestChecks" framework from private repo

CONTRIBUTING.md
=> fix(docs): Add note about commit messages

lib/config/config.js
=> fix(config): remove mockmyid rate limit, add second restmail

.travis.yml, lib/block_reasons.js, lib/config/config.js, lib/reputationService.js, lib/server.js, test/memcache-helper.js, test/remote/check_reputation_tests.js, test/remote/check_tests.js, test/remote/failed_login_attempt_tests.js, test/remote/memcache_error_tests.js, test/remote/password_reset_tests.js, test/remote/send_violations_tests.js, test/test_reputation_server.js, test/test_reputation_server_stub.js
Add feature flag to check reputation IPs on the `/check` route and block requests below `REPUTATION_SERVICE_BLOCK_BELOW`.
Functional Tests:
setup:
* run memcached and postgres-ip4r docker container
* run tigerblood: `TIGERBLOOD_DSN="user=tigerblood dbname=tigerblood sslmode=disable" ./tigerblood`
* run customs server: `REPUTATION_SERVICE_ENABLE=true REPUTATION_SERVICE_ENABLE_CHECK=true REPUTATION_SERVICE_BLOCK_BELOW=50 node bin/customs_server.js`
Check `/check` against running tigerblood server:
```
curl -w '\n' -v -H "Content-Type: application/json" "http://127.0.0.1:7000/check" -d '{"email": "me@example.com", "ip
": "192.0.2.1", "action": "accountCreate"}'
{"block":true,"retryAfter":900,"unblock":true,"suspect":false}
{"name":"customs-server","hostname":"gguthe-23818","pid":16752,"level" …
```
=> feat(ipreputation): Use IP reputation service from /check

test/test_server.js
This PR adds support for debugging into child processes. Similar to auth-server PR, https://github.com/mozilla/fxa-auth-server/pull/1550
=> refactor(tests): Add ability to debug child processes

bin/customs_server.js
Fixes an issue where the custom server process didn't exit properly on startup errors.
=> fix(startup): Exit process on any startup error.

npm-shrinkwrap.json, package.json, scripts/tap-coverage.js, test/customs_server_stub.js, test/local/ban_tests.js, test/local/email_record_tests.js, test/local/ip_blocklist_tests.js, test/local/ip_email_record_tests.js, test/local/ip_record_tests.js, test/local/sms_record_tests.js
=> fix(tests): remove old code coverage tool

lib/config/config.js, lib/reputationService.js, npm-shrinkwrap.json, package.json, test/remote/check_reputation_tests.js, test/remote/send_violations_tests.js, test/test_reputation_server.js, test/test_reputation_server_stub.js
Refs: https://github.com/mozilla/fxa-customs-server/issues/166
Updates ip rep js client to 2.0.1 and makes the relevant test and server changes.
I didn't update the shrinkwrap.  Is that part of the release process or should it be in the PR?
=> Fix rep service config

npm-shrinkwrap.json, package.json, scripts/config-set.js
=> fix(config-set): Don't attempt to merge array-valued config items.

lib/reputationService.js
r? - @vbudhram, @g-k 
Add some more logging, so 200 vs. 400 responses can be seen in logs. 
May make more sense to review with `?w=1` due to whitespace changes.
=> fix(reputation): add more (positive) logging to reputation service requests

bin/customs_server.js
=> fix(shutdown): Fix deferred call of process.exit(code).

docs/api.md
Ref: https://github.com/mozilla/fxa/blob/ae28a78ef05241c0de8daceeadb0d42d92a41580/features/FxA-53-send-sms/README.md#customs-server-vbudhram
@shane-tomlinson r?
=> fix(docs): Add notes for sms

lib/config/config.js, lib/sms_record.js, test/remote/too_many_sms.js
Fixes #185 and also add some supporting test cases.
=> fix(tests): Update config and testing for sms

lib/server.js, npm-shrinkwrap.json, package.json
=> fix(security): escape json output

README.md, lib/email_record.js, test/remote/too_many_sms.js
This PR adds ability to rate limit SMS actions by email.
Fixes #188 
@rfk @seanmonstar r?
=> fix(sms): Add ability to rate-limit sms by email

README.md
=> fix(docs): document the dependency on memcached

Dockerfile-build
=> fix(newrelic): newrelic native requires python, gyp, c++; update node@6.12.0

lib/config/config.js, lib/server.js, lib/settings/allowed_ips.js, lib/settings/allowed_phone_numbers.js, scripts/config-list.js, scripts/config-set.js, test/memcache-helper.js, test/remote/config_update_tests.js, test/remote/too_many_sms.js
=> feat(sms): Add an allow list of non-rate limited phone numbers for testing.

.travis.yml, lib/ip_blocklist.js, package.json
Trial balloon to see if this fixes #212; it makes the demo script from that issue work OK, so I'm hopeful...
=> fix(blocklist): Fix use of setImmediate to work with node 8

lib/config/config.js, lib/server.js, npm-shrinkwrap.json, package.json
Fixes https://github.com/mozilla/fxa-customs-server/issues/221
=> feat(logs): add Sentry error logs

lib/actions.js, test/remote/too_many_verify_codes.js
Fixes #222 
Opted to do a dynamic test to avoid duplication. Also took the chance to update to ES6 [syntax](https://github.com/mozilla/fxa-customs-server/pull/225/commits/02acdb2daef2d8f63998e251f4796976e9c773ee).
=> feat(token): Add rate limit for tokenCodes

npm-shrinkwrap.json, package.json
See discussion starting at https://bugzilla.mozilla.org/show_bug.cgi?id=1447452#c18.
@mozilla/fxa-devs r?
=> chore(deps): update ip-reputation-js-client

npm-shrinkwrap.json, package.json
=> fix(npm): update shrinkwrap

.nsprc, npm-shrinkwrap.json, package.json
Fixes https://github.com/mozilla/fxa-customs-server/issues/243
=> fix(deps): Update ip rep client to v3

scripts/test-local.sh
=> fix(tests): fix test-local.sh bug introduced in d177360

CHANGELOG.md, Dockerfile-build, npm-shrinkwrap.json, package.json, scripts/test-local.sh
=> merge train-114 into master

circle.yml
ref: mozilla/fxa#302
r? - @mozilla/fxa-devs
=> fix(circle): docker run --rm -it fxa-customs-server:build npm ls --production fxa#302

CHANGELOG.md, npm-shrinkwrap.json, package.json
@mozilla/fxa-devs - r?
I forgot to reverse merge this last time.
=> Release v1.116.0

CHANGELOG.md, npm-shrinkwrap.json, package.json
=> Release v1.120.0

CHANGELOG.md, npm-shrinkwrap.json, package.json
=> Merge train-129 into master

lib/settings/limits.js, lib/settings/requestChecks.js, lib/utils.js, test/local/settings_tests.js
Fixes #319, using the same approach as #315.
@mozilla/fxa-devs r?
(I'll tag a ~~point~~ train-130 release if this is merged)
=> fix(logs): preserve homogeneity of more log properties

lib/config/config.js, lib/dataflow.js, lib/server.js, npm-shrinkwrap.json, package.json, test/local/dataflow_tests.js
Hook up to GCP PubSub to listen for fraud detection events
from the DataFlow fraud detection pipeline.
fixes #311
=> feat(fraud-detection): Listen for DataFlow fraud detection events

npm-shrinkwrap.json, package.json
Update:
* tap
* js-yaml
* grunt
=> fix(deps): Fix the audit warnings.

CHANGELOG.md, npm-shrinkwrap.json, package.json
=> chore(release): Merge train-134 into master.
