mozilla/fxa-customs-server

grunttasks/bump.js
grunttasks/copyright.js
grunttasks/jshint.js
grunttasks/version.js
npm-shrinkwrap.json
package.json
test/remote/block_email_tests.js
test/remote/block_ip_tests.js
test/remote/check_tests.js
test/remote/email_normalization.js
test/remote/failed_login_attempt_tests.js
test/remote/never_blocked.js
test/remote/password_reset_clears_bad_logins.js
test/remote/password_reset_tests.js

The first commit for test is to quiet a jshint warning for "'obj' is defined but never used". Previously jshint was passing since it was not linting these files. 
The second commit is just like fxa-auth-server and fxa-auth-db-mysql repos, but review the file matching patterns. r? @chilts @pdehaan

Add task for tagging release and fix some jshint whining

---

config/config.js
npm-shrinkwrap.json
package.json

Fixes #84.
There's some dependency problem with restify and I didn't want to try to debug an upgrade to the new release, which is a major API version bump.  So I added a `--force` to the dependency checker.

chore(config): Update convict and switch on strict validation.

---

npm-shrinkwrap.json
package.json

I went to update shrinkwrap, and the version of `ass` we use causes a weird error with shrinkwrap. So use the version we use in other repos. 
@chilts r?

chore(shrinkwrap): update ass to what other modules use; update shrinkwrap

---

.travis.yml

I tried to update to grunt-nsp but that spewed errors about extraneous modules under node_modules/grunt-nsp. So just removing this broken test to fix travis.

fix(travis): remove broken validate-shrinkwrap

---

config/config.js

Just completing cleanup of awsbox removal.

chore(docs): remove misleading reference to awsbox

---

config/README.md
lib/config/config.js

This was lost in #98 and broke new fxa-dev deployments.

fix(config): restore top-level "config" dir for $(NODE_ENV).json files.

---

README.md
lib/config/config.js
lib/email_record.js
lib/ip_record.js
lib/server.js
test/local/ip_record_tests.js
test/remote/too_many_account_status_check.js

This PR adds a new route to the customs server, `POST /accountStatus`. This is used to rate-limit requests by ip address, for getting an account's status. This is a dependency for https://github.com/mozilla/fxa-auth-server/pull/1184
Fixes #96 
@rfk this is what you had in mind? r?

feat(api): Add account status check with rate limiting

---

lib/actions.js

This ensures we treat all actions with similar affects as equivalent and rate-limit them together.  It's especially relevant for the many different ways that one can discover whether a particular account exists or not.
Note that the rate-limiting for account status check now counts the number of unique emails accessed within the rate-limiting window, not the total number of checks performed.  This should help mitigate the risk of adding all these other actions into that category.  We may still find we need to raise the limit on that though.

fix(check): Include more action names in various checks.

---

lib/allowed_email_domains.js
lib/config/config.js
lib/server.js
test/memcache-helper.js
test/remote/block_email_tests.js
test/remote/config_update_tests.js

Similar to our existing `ALLOWED_IPS` setting, this PR gives us the ability to allowlist a set of email address domains, exempting them from rate-limits and blocks.  This is likely very handy for QA, both for ourselves (where we currently have to raise rate limits in stage) and for others (e.g. https://bugzilla.mozilla.org/show_bug.cgi?id=1269425)
A couple of notes:
* The `allowed_email_domains.js` file is a copy-paste of the existing `allowed_ips.js` file; I considered a refactor to extract shared logic but decided not to invest in it at this time
* The checking of the allowlist is only done at the point where we are actually about to block an email, which means there should be no additional overhead for legitimate users
@seanmonstar r?

feat(email): Add config option to avoid blocking certain email domains

---

lib/config/config.js
lib/email_record.js
lib/limits.js
lib/server.js
test/local/email_record_tests.js
test/memcache-helper.js
test/remote/never_blocked.js
test/remote/too_many_bad_logins.js
test/remote/too_many_login_checks.js

fixes #120 
I made this into two commits. The first commit removes all references to `isWayOverBadLogins` and anywhere where `lockout` is referenced. The second commit also removes `lf` (loginFailures) from EmailRecord. I was less sure whether this would be used in the future for some feature, perhaps email captcha. I suppose we can always go back to this commit and update as needed.
@rfk and @seanmonstar - r?

feat(server): Remove account lockout.

---

bin/customs_server.js
lib/newrelic.js
npm-shrinkwrap.json
package.json

Now for customs-server...
svcops would like to make use of New Relic. This PR just makes it possible to load the module if explicitly configured. Further configuration will happen with puppet in the circusd environment (unless we have to set so many switches that a sane configuration file makes sense).
r? @rfk

feature(newrelic): add optional newrelic integration

---

lib/limits.js
test/remote/config_update_tests.js

Previously this was not pushing the `uidRateLimit` settings object into memcached, so it was failing when it tried to load it back out.  @vbudhram r?

fix(settings): Fix reloading of nested settings from mecmached

---

npm-shrinkwrap.json
package.json

Seems this was triggering an NSP warning: https://nodesecurity.io/advisories/106
The customs server isn't exposed to the public, but we should update anyways.

fix(dependencies): update restify to 4.1.1

---

.travis.yml
lib/actions.js
lib/config/config.js
lib/email_record.js
lib/limits.js
lib/server.js
test/local/email_record_tests.js
test/memcache-helper.js
test/remote/unblock_tests.js

cc https://github.com/mozilla/fxa-auth-server/pull/1471

feat(unblock): add unblock rate limits

---

lib/config/config.js
test/remote/block_ip_tests.js

Per conversation in https://github.com/mozilla-services/puppet-config/issues/2330, let's default this to an empty list to make life easier for Ops.  They were overriding these values in production anyway.

chore(config): Don't set allow ALLOWED_IPS by default.

---

lib/ip_blocklist.js

Per https://nodejs.org/api/fs.html#fs_class_fs_stats, uses `getTime()` on mtime, for use in comparisons.
Fixes #142

fix(blocklist): Convert date to milliseconds for file comparison

---

lib/limits.js
lib/requestChecks.js

The logger used here (bunyan) treats 'msg' as a place to write its own formatted interpretation of the log message, so don't use it for our own purposes.  Instead let's log it under the name "message".  Bleh, I know, but simplest fix to get production logging up and running in the next train.  @jrgm r?
Fixes #140

fix(logging): Don't attempt to log a 'msg' field.

---

lib/ip_record.js
test/local/ip_record_tests.js

As noted in https://github.com/mozilla/fxa-content-server/issues/4324, the per-ip-address login rate-limiting is over-counting failed logins from a single email address.  This fixes it to only take the max-weighted errno from each unique email address.
Amusingly, this bug was causing the existing "addBadLogins works per IP" to pass, when it should have been failing.
@shane-tomlinson since this unblocks signin unblock, r?

fix(ip_record): Correctly total bad logins by unique email address.

---

test/remote/send_violations_tests.js

to make the test less flaky
refs: https://github.com/mozilla/fxa-customs-server/issues/153
I pulled this out of https://github.com/mozilla/fxa-customs-server/pull/152 since something else is going on there with the `/check` changes.

fix(test): increase rateLimitInterval for send_violation_tests

---

npm-shrinkwrap.json
package.json
scripts/config-set.js

This makes it easier to change a single setting while leaving all the others alone.  Fixes #127.  @jrgm r?

feat(config): Merge with existing config when writing to memcache.

---

lib/email_record.js
lib/ip_email_record.js
lib/ip_record.js
test/local/email_record_tests.js
test/local/ip_email_record_tests.js

Fixes #158; @vbudhram r?; /cc @g-k 
Previously, the code would round your ban period down to the
nearest integral number of seconds.  Since the ban duration in
tests is only 1 second, this would occasionally cause it to be
rounded down to zero, leading to flaky test failures.
We now round the ban priod *up* to the nearest integral number
of seconds, which shouldn't have any significant impact on users
in production, but makes the tests much simpler to reason about.

fix(retryAfter): Round blocking periods up instead of down.

---

lib/allowed_email_domains.js
lib/allowed_ips.js
lib/bans/sqs.js
lib/ip_blocklist.js
lib/limits.js
lib/requestChecks.js

These timers are all just for background polling for updates, they don't need to keep the event-loop alive.  Unref them.

fix(timers): Unref all the update-polling timers.

---

lib/actions.js
lib/config/config.js
lib/ip_record.js
lib/limits.js
lib/server.js
lib/sms_record.js
test/local/sms_record_tests.js
test/memcache-helper.js
test/remote/too_many_sms.js

Fixes https://github.com/mozilla/fxa-customs-server/issues/160
This PR adds the following support to the custom's server:
Connects with https://github.com/mozilla/fxa-features/issues/53, https://github.com/mozilla/fxa-auth-server/issues/1628

feat(sms): Add support for rate-limiting sms actions

---

npm-shrinkwrap.json
package.json

Bump IP Reputation JS client to version 2.1.1 which has keepalive enabled.
This should help fix some of the TCP RSTs and timeouts jrgm and I saw when we enabled a canary instance in prod last week.

chore(package): Use ip-rep service client with keepalive enabled

---

lib/ip_record.js
lib/server.js
test/remote/too_many_sms.js

This PR correctly rate limits when a user has sent more than 5 sms from an ip address. Previously, the the rate limiting was `rate-limit when 5 unique sms requests sent from this ip address`. Updated tests to be more reflective of this scenario.
Fixes #190
@rfk r?

fix(tests): Update rate limit sms by ip address

---

lib/actions.js

This PR adds rate-limiting to all endpoints that send emails for the add secondary email feature. It is a one liner because we reuse the verify code and resend code endpoints in add secondary emails. The only other endpoint that sends an email is the create email operation.
Fixes #180 
@vladikoff r?

feat(emails): Add `createEmail` to email sending endpoints

---

lib/actions.js
lib/config/config.js
lib/ip_record.js
lib/server.js
lib/settings/limits.js
test/remote/block_ip_tests.js
test/remote/check_ip_only_tests.js
test/remote/check_reputation_tests.js
test/remote/ip_blocklist_disable.js
test/remote/ip_blocklist_tests.js
test/remote/too_many_signin_codes.js

Fixes #201.
* Adds a new endpoint `/checkIpOnly` that rate-limits purely against an IP address, with no requirement for an email address or a uid.
* Adds a new class of action that I'm calling `ACCOUNT_ACCESS_ACTION`, with one eye on phase 4 of connect-another-device. I needed a new action because I have no email address to rate-limit against, so I can't use `CODE_VERIFYING_ACTION` for instance.
* Refactors some of the common code to make `email` an optional parameter. Doing this necessitated changing the order of some arguments and returned promises, but I think I covered all the calling code in my changes.
The intention is for the proposed auth server endpoint for consuming signinCodes (see mozilla/fxa-auth-server#1882) to hit `/checkIpOnly` with `{"action":"consumeSigninCode"}` and the …

feat(actions): add consumeSigninCode as an ACCOUNT_ACCESS_ACTION

---

lib/ip_record.js
test/remote/check_tests.js
test/remote/too_many_signin_codes.js

Fixes #205. Supercedes #206.
When running the content server functional tests, lots of requests to `/check` originate from the same IP address. These cause the rate limit flag to be set in `IpRecord`, but the request itself is not blocked because the email address matches the test in `allowWhitelisted`.
This is all fine until requests to `/checkIpOnly` start turning up. Now, the `IpRecord` is still marked as rate-limited when it is fetched from memcached, but we have no email address to whitelist on. So those requests get blocked, even though the specific action they're checking is below its threshold.
This PR fixes the issue using @rfk's preferred fix from https://github.com/mozilla/fxa-customs-server/issues/205#issuecomment-310551201, returning zero from `IpRecord::update` if the `aa` …

(iprecord): ignore prior rate-limiting for account access actions

---

bin/customs_server.js
npm-shrinkwrap.json
package.json

This PR supersedes #284 which just added a futureproofing comment, to update the newrelic module to latest 2.3.2, with an npm run shrink using npm@2.15.1
It would be helpful to merge this down to fxa-customs-server-private so I can run this in stage!
r? - @vladikoff

Dockerpush fix newrelic must be first

---

docs/api.md
lib/server.js

Changes:
* Add API docs for `POST /checkIpOnly`
* Fix an apparent typo in the op for the missing params error log
Checked that:
* the example from the docs `curl -w '\n' -v -H "Content-Type: application/json" "http://127.0.0.1:7000/checkIpOnly" -d '{"ip":"192.0.2.1","action":"accountCreate"}'` returns the expected result
* ran tests locally, a bunch fail but I don't think it's related to these changes

Check ip only doc and log fix

---

README.md
scripts/test-local.sh
test/memcache-helper.js

Have added the lines to start memcached, not checking if it is running already as it does nothing if it is already running. spawnSync makes it waiting forever so i am using spawn only.

fix(test): #228 Start memcached as part of 'npm test'

---

lib/config/config.js
lib/record.js
lib/server.js
lib/utils.js
test/local/record_tests.js
test/remote/too_many_totp_codes.js

Fixes #226 
This PR adds rate limiting to actions that involve checking a TOTP code (only `verifyTotpCode` atm ). Unfortunately, while adding this rate limit, I could not re-use the existing rate limiting structure for ip and email based actions since those limits are defined `config.limits.rateLimitIntervalSeconds`. The TOTP rate limit requirement is 2 checks every 30 seconds (rate the codes are generated).
To support this feature, I decided to build off https://github.com/mozilla/fxa-customs-server/pull/174, which had a lofty goal of refactoring all the things. This PR is a smaller subset that adds support for creating a custom rule for actions and checking limits.
* To maintain backwards comp, a new route is used `/checkWithRule`
* Added a generic record class that stores custom limits …

feat(totp): add totp rate limits

---

test/memcache-helper.js
test/remote/block_ip_tests.js
test/remote/send_violations_tests.js
test/remote/too_many_verify_codes.js
test/utils.js

I was setting up a new computer yesterday and found that these tests depended on a previous tests state which caused some test failures. I suspect that the older computer was slow enough that the limits were reset before the next test. This fixes the issue my using unique ips, emails and actions when needed.
Unfortunately, there are probably more tests that have shared states but it would be more work to find and fix them than to do a complete refactor such as https://github.com/mozilla/fxa-customs-server/pull/174.

fix(tests): fix dependent tests

---

lib/config/config.js

As discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1448854#c5; @philbooth r?

fix(sms): Reduce sms rate-limit interval to half an hour.

---

README.md

I do a bunch of private-repo wrangling when tagging customs-server that's probably not obvious to others, so I thought I better write it down.  @mozilla/fxa-devs r?

chore(docs): Add documentation on tagging private releases.

---

lib/reputationService.js
npm-shrinkwrap.json
package.json
test/test_reputation_server_stub.js

Update ip-reputation-js-client to v4 which includes the changes:
* remove the add method (I don't see customs-server using this anywhere)
* downcased field names (fixed Reputation to reputation and Violation to violation; don't see any other occurrences)
* switch to the memcached backed [iprepd](https://github.com/mozilla-services/iprepd) backend
* add eslint changes and fixes
cc @ameihm0912 who wants to make sure the client tracks failed requests and latency (in this PR or a new separate one)

fix(deps): update ip rep client to v4

---

scripts/test-local.sh

test-local.sh specifies /bin/sh as an interpreter, but contains the [[
bash builtin which fails on systems where /bin/sh is not bash or is
running in a compatibility mode.
Updates test-local.sh to use a standard test command.

fix(tests): remove bash builtin from test-local.sh

---

lib/reputationService.js
npm-shrinkwrap.json
package.json
test/remote/check_reputation_tests.js
test/test_reputation_server_stub.js

- Update ip-reputation-js-client to 4.0.2, which contains the addition of request timing info (https://github.com/mozilla-services/ip-reputation-js-client/commit/e0d3d58e53a9c01cd46c669809f7daa0fb3a0b03)
- Include request timing info in reputation service logging
- Add tests using ip-reputation-js-client to confirm addition of timing data
- Update stub reputation service to remove a deprecated endpoint

Updates to reputation service integration

---

test/integration/reputation/README.md
test/integration/reputation/docker-compose.yml
test/integration/reputation/iprepd.yaml
test/integration/reputation/iprepd_tests.js
test/memcache-helper.js

Add framework for integration testing between fxa-customs-server and
iprepd (newer version of Tigerblood). The existing set of tests included a stub
reputation server; this conducts similar testing but uses the actual
reputation service backend.
Note: this doesn't actually hook it into the CI yet but can be executed manually
```
docker build -f Dockerfile-build fxa-customs-server:build
cd test/integration/reputation
docker-compose build
docker-compose run customs
docker-compose down
```

test(reputation): adds compose based integration test with iprepd

---

lib/actions.js

Fixes https://github.com/mozilla/fxa-auth-server/pull/2518#discussion_r202904055
Since we are adding to an existing action, no additional test coverage was needed.
@mozilla/fxa-devs r?

feat(code): add `recoveryKeyExists` to account status actions

---

npm-shrinkwrap.json
package.json

Makes timeout param include DNS resolution and `connect()` not just time since last byte after a connection is established.
https://github.com/mozilla-services/ip-reputation-js-client/pull/24

fix(deps): update ip-reputation-js-client to 4.1.0

---

lib/server.js

(Same as fxa-auth-db-mysql):
Hey @vladikoff. I biffed setting this on my first try. This is the correct object location, and I've verified by watching tcpdump/netstat in stage with this fix that connections are held open until idle for 2 minutes.

fix(restify): set keepAliveTimeout correctly on api.server object

---

npm-shrinkwrap.json
package.json
scripts/tls-shrink.sh

I noticed that tls-shrink was not included in this repo like our others, so added it while I was removing the "^" prefix on the audit-filter version.
follow on from #280
@mozilla/fxa-devs - r?

feat(deps): Add tls-shrink, remove "^" prefix on audit-filter version

---

.eslintrc
lib/settings/limits.js
npm-shrinkwrap.json
package.json
test/local/settings_tests.js

Fixes #314.
Stackdriver doesn't like it when properties in logged objects change their types. This change just ensures that our `limits.validate.changed` log line doesn't overload `current` and `future` properties for all the different limit types.
@mozilla/fxa-devs r?
/cc @jbuck

fix(logs): preserve homogeneity of log properties

---

lib/bans/handler.js
lib/record.js
lib/records.js
lib/server.js
lib/user_defined_rules.js
npm-shrinkwrap.json
package.json
test/local/ban_tests.js
test/local/records_tests.js

server.js has a whole bunch of mixed concerns, part of which was record retrieval
and loading/checking user defined rules.
This PR extracts record handling logic as well as user defined rules logic
into their own modules.
Loading/saving records can now be done through a common interface. fetchRecords no longer
holds the assumption that an ip address will be passed in. setRecord no longer requires
passing in a key as the key is stored on the record, and setRecords now only accepts records
instead of it's confusing signature.  It's now possible to define non-enumerable
properties on a record that are not saved when serialized.
I started to use async/await to simplify logic where it made sense as well as
started down the path to using native promises in places.
Note, no remote tests are …

refactor(server): Extract and simplify record retreival/storage, user defined rules.
